package docs

// This file contains Swagger/OpenAPI documentation for the API
// Generated by swag init or manually updated
// Swagger serves as API contract and generates interactive docs at /swagger/index.html

const SwaggerInfo = `{
  "swagger": "2.0",
  "info": {
    "title": "Ecom API",
    "description": "E-Commerce API with user authentication",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "schemes": ["http", "https"],
  "paths": {
    "/register": {
      "post": {
        "summary": "Register new user",
        "description": "Creates a new user account and returns auth token",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {"type": "string"},
                "password": {"type": "string"},
                "first_name": {"type": "string"},
                "last_name": {"type": "string"}
              }
            }
          }
        ],
        "responses": {
          "201": {"description": "User created successfully"}
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Login user",
        "description": "Authenticates user and returns auth token",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {"type": "string"},
                "password": {"type": "string"}
              }
            }
          }
        ],
        "responses": {
          "200": {"description": "Login successful"}
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Get user",
        "description": "Retrieves user data by ID",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {"description": "User found"},
          "404": {"description": "User not found"}
        }
      }
    }
  }
}`
